# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  gaucornerapi:
    image: gaucornerapi
    build:
      context: .
      dockerfile: GauCorner.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5152:5152
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
